"""initial schema

Revision ID: 5fb166dffda7
Revises: 
Create Date: 2026-09-21 00:24:00.112994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb166dffda7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devig_method', sa.Enum('MULTIPLICATIVE', 'POWER', 'SHIN', name='devig_method'), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('kelly_cap_pct', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('edge_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stale_odds_minutes', sa.Integer(), nullable=False),
    sa.Column('default_bankroll', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_loss_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('bankrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bankrolls'))
    )
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_anj_licensed', sa.Boolean(), nullable=False),
    sa.Column('is_sharp_reference', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmakers')),
    sa.UniqueConstraint('slug', name=op.f('uq_bookmakers_slug'))
    )
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sports')),
    sa.UniqueConstraint('slug', name=op.f('uq_sports_slug'))
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_competitions_sport_id_sports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions')),
    sa.UniqueConstraint('slug', name=op.f('uq_competitions_slug'))
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('normalized_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_participants_sport_id_sports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    op.create_index(op.f('ix_participants_normalized_name'), 'participants', ['normalized_name'], unique=False)
    op.create_table('competition_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_aliases_competition_id_competitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_aliases')),
    sa.UniqueConstraint('provider', 'raw_name', name='uq_competition_alias_provider_raw')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('home_participant_id', sa.Integer(), nullable=False),
    sa.Column('away_participant_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINISHED', 'CANCELLED', name='event_status'), nullable=False),
    sa.Column('external_ref', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['away_participant_id'], ['participants.id'], name=op.f('fk_events_away_participant_id_participants')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_events_competition_id_competitions')),
    sa.ForeignKeyConstraint(['home_participant_id'], ['participants.id'], name=op.f('fk_events_home_participant_id_participants')),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_events_sport_id_sports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('participant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_participant_aliases_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_aliases')),
    sa.UniqueConstraint('provider', 'raw_name', name='uq_participant_alias_provider_raw')
    )
    op.create_table('event_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.Enum('ONE_X_TWO', 'MONEYLINE', 'OVER_UNDER', name='market_type'), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_markets_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_markets')),
    sa.UniqueConstraint('event_id', 'market_type', 'line', name='uq_event_market_type_line')
    )
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_market_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('HOME', 'DRAW', 'AWAY', 'OVER', 'UNDER', 'PARTICIPANT_WIN', name='selection_code'), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_market_id'], ['event_markets.id'], name=op.f('fk_selections_event_market_id_event_markets')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_selections_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selections')),
    sa.UniqueConstraint('event_market_id', 'code', 'participant_id', name='uq_selection_market_code_participant')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], name=op.f('fk_odds_snapshots_bookmaker_id_bookmakers')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_odds_snapshots_selection_id_selections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    op.create_index(op.f('ix_odds_snapshots_captured_at'), 'odds_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_selection_bookmaker_time', 'odds_snapshots', ['selection_id', 'bookmaker_id', 'captured_at'], unique=False)
    op.create_table('paper_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bankroll_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('odds_taken', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('true_probability_at_placement', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('fair_odds_at_placement', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('edge_at_placement', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('devig_method_at_placement', sa.Enum('MULTIPLICATIVE', 'POWER', 'SHIN', name='devig_method_bet'), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closing_odds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('clv', sa.Numeric(precision=7, scale=5), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', 'VOID', name='bet_status'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bankroll_id'], ['bankrolls.id'], name=op.f('fk_paper_bets_bankroll_id_bankrolls')),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], name=op.f('fk_paper_bets_bookmaker_id_bookmakers')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_paper_bets_selection_id_selections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_bets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_bets')
    op.drop_index('ix_odds_snapshots_selection_bookmaker_time', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_captured_at'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('selections')
    op.drop_table('event_markets')
    op.drop_table('participant_aliases')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_table('events')
    op.drop_table('competition_aliases')
    op.drop_index(op.f('ix_participants_normalized_name'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('competitions')
    op.drop_table('sports')
    op.drop_table('bookmakers')
    op.drop_table('bankrolls')
    op.drop_table('app_settings')
    # ### end Alembic commands ###

    # Postgres ENUM types are not dropped automatically when their owning
    # table is dropped; remove them explicitly so downgrade is reversible.
    bind = op.get_bind()
    for enum_name in (
        "devig_method_bet",
        "bet_status",
        "selection_code",
        "market_type",
        "event_status",
        "devig_method",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
