"""scope participant alias by sport

Revision ID: a88ed9dfa4e9
Revises: 5fb166dffda7
Create Date: 2026-09-21 00:35:22.968375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88ed9dfa4e9'
down_revision: Union[str, None] = '5fb166dffda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_aliases', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_participant_alias_provider_raw', 'participant_aliases', type_='unique')
    op.create_unique_constraint('uq_participant_alias_provider_raw_sport', 'participant_aliases', ['provider', 'raw_name', 'sport_id'])
    op.create_foreign_key(op.f('fk_participant_aliases_sport_id_sports'), 'participant_aliases', 'sports', ['sport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_participant_aliases_sport_id_sports'), 'participant_aliases', type_='foreignkey')
    op.drop_constraint('uq_participant_alias_provider_raw_sport', 'participant_aliases', type_='unique')
    op.create_unique_constraint('uq_participant_alias_provider_raw', 'participant_aliases', ['provider', 'raw_name'])
    op.drop_column('participant_aliases', 'sport_id')
    # ### end Alembic commands ###
