"""add provider_sport_key to competitions

Revision ID: c9ebc2093299
Revises: a88ed9dfa4e9
Create Date: 2026-09-21 06:04:06.742134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ebc2093299'
down_revision: Union[str, None] = 'a88ed9dfa4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('provider_sport_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'provider_sport_key')
    # ### end Alembic commands ###
